#Uses that of the latest image of node.
FROM node:latest

#The working directory running this dockerfile is in /app.
WORKDIR /app

#Copies that of the package.json files from that of project directory unto that of the working directory.
COPY package*.json ./ 

#Runs that of installing the node package dependencies.
RUN npm install

#Copies that of the files seen in backend and puts it in the working directory.
COPY . .

#Exposes 3001 port. This connects to the server.js's container.
EXPOSE 3001

#Runs that of the server with this command.
CMD ["npm", "start"]